- tap:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-fonts
    - homebrew/core

- brew:
    - gnupg
    - python@3.8
    - mas

- cask:
    - font-hack-nerd-font
    - google-chrome
    - iterm2
