- cask:
    - iterm2

- shell:
    - 
      command: cp terminals/iterm2/com.googlecode.iterm2.plist ~/Library/Preferences/
      stdin: true
      stdout: true
      description: Making zsh the default shell
      quiet: false