- brew:
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting

- link:
    ~/.zshrc:
        path: shells/zsh/zshrc

- shell:
    - 
      command: "~/.dotfiles/scripts/zsh.sh"
      stdin: true
      stdout: true
      description: Making zsh the default shell
      quiet: false

- shell:
    - 
      command: "gem install colorls"
      stdin: true
      stdout: true
      description: Installing colorls
      quiet: false