execute pathogen#infect()
"call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
syntax enable
set background=dark
colorscheme dracula
filetype plugin indent on
set tabstop=4
set expandtab
set guifont=Monaco:h14
